Parameters:
  VpcEndpointId:
    Description: Enter a VPC endpoint with type interface for the execute-api service to enable private PCUI implementation. When enabled, the API will only accept requests from within the given VPC.
    Type: String
    Default: ''

Conditions:
  IsPrivate: !Not [!Equals [!Ref VpcEndpointId, ""]]

Mappings:
  ParallelClusterUI:
    Constants:
      Version: 2024.03.0 # format YYYY.MM.REVISION

Resources:

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ParallelClusterUI
      Description: ParallelClusterUI Lambda Proxy
      Policy:
        Fn::If:
          - IsPrivate
          - Version: "2012-10-17"
            Statement:
              - Effect: "Deny"
                Principal: "*"
                Action: "execute-api:Invoke"
                Resource: "execute-api:/*"
                Condition:
                  StringNotEquals:
                    aws:sourceVpce: !Ref VpcEndpointId
              - Effect: "Allow"
                Principal: "*"
                Action: "execute-api:Invoke"
                Resource: "execute-api:/*"
          - Version: "2012-10-17"
            Statement:
            - Effect: "Allow"
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource: "execute-api:/*"
      EndpointConfiguration:
        Types:
          - !If [ IsPrivate, PRIVATE, REGIONAL ]
        VpcEndpointIds:
          - !If [ IsPrivate, !Ref VpcEndpointId, !Ref AWS::NoValue ]
      Tags:
        - Key: 'parallelcluster:ui:version'
          Value: !FindInMap [ParallelClusterUI, Constants, Version]

Outputs:
  ApiGatewayRestApi:
    Description: 'Api gateway'
    Value: !Ref ApiGatewayRestApi

  RootResourceId:
    Description: Root resource Id of Api Gateway
    Value: !GetAtt ApiGatewayRestApi.RootResourceId

  RedirectURL:
    Description: 'Url to callback for login.'
    Value: !Sub
      - https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/pcui/login
      - Api: !Ref ApiGatewayRestApi
